# ----------- CONFIGURABLE START -----------
title:            "Hung"
description:      "blog"
url:              https://lazyval.com
signoff:          "Hung"
# facebook_appid:
google_analytics: UA-145889271-1
share:            false


links:
  - name:         "&raquo; Hung "
    url:          /
    external:     false
  - name:         "Resume &laquo;"
    url:          /resume
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /:categories/:title
defaults:
  - values:
      layout: "default"
timezone: Asia/Ho_Chi_Minh
future: true